version: "{build}"

# FIXME: currently does not work with IPython: get error "stdin is not a tty"
# when trying to test version of IPython in configure

environment:
  global:
    VERBOSE: 1 # Get test logs in output
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSYSTEM: MSYS
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSYSTEM: MINGW64
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSYSTEM: MINGW32

init:
  - cmd: git config --global core.autocrlf input

install:
  - cmd: C:\msys64\usr\bin\bash.exe -lc "cd c:/projects/mit && ./build-aux/appveyor-install.sh"

# FIXME: In-place mit doesn't work, so remove pforth after bootstrap
# (It would otherwise be tested on mingw32.)
build_script:
  - cmd: C:\msys64\usr\bin\bash.exe -lc "cd c:/projects/mit && ./bootstrap && rm -rf src/features/pforth && ./configure --enable-silent-rules && make && make install && make check"
