os: linux
language: c
dist: bionic
services: docker

addons:
  homebrew:
    packages:
      - help2man
    update: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - python3.8
      - texlive-latex-extra
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - tex-gyre
      - help2man
      - latexmk
      - hevea

env:
  global:
    - VERBOSE=1

# Setup for Docker adapted from https://github.com/junaruga/ci-multi-arch-test
.com.github.junaruga.ci-multi-arch-test.jobs-definitions:
  - &test_in_container
    install:
      - ls /proc/sys/fs/binfmt_misc/
      - |
        if [ "$(uname -m)" = x86_64 ]; then
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        fi
      - ls /proc/sys/fs/binfmt_misc/
      - docker build --tag test --build-arg BASE_IMAGE=${BASE_IMAGE} .
    script:
      - docker run --tty --rm --env CC=${CC} test ./build-aux/travis-build.sh

jobs:
  include:
    - os: osx
    - env:
        - MATRIX_EVAL="CC=gcc-8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [gcc-8]
    - compiler: gcc
      env:
        - BASE_IMAGE=i386/ubuntu
        - BENCH_TEST=yes
      <<: *test_in_container
    - compiler: clang
      env:
        - BASE_IMAGE=i386/ubuntu
        - BENCH_TEST=yes
      <<: *test_in_container
    - env:
        - ASAN=yes
        - LSAN_OPTIONS="verbosity=1:log_threads=1"


before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./build-aux/travis-build.sh
  # "BENCH_TEST=yes" can wait for a long time
  - if [[ "$BENCH_TEST" == "yes" ]]; then travis_wait make bench; fi
