language: c
sudo: true
dist: bionic

addons:
  homebrew:
    packages:
    - help2man
    update: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - texlive-latex-extra
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - tex-gyre
      - help2man
      - latexmk
      - hevea

env:
  global:
    - VERBOSE=1

matrix:
  include:
    - os: osx
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [gcc-8]
    - env:
      - BENCH_TEST=yes
      - CONFIGURE_ARGS=("CC=\"gcc -m32\"")
    - compiler: clang
      env:
        - BENCH_TEST=yes
        - CONFIGURE_ARGS=("CC=\"gcc -m32\"")
    - env:
      - ASAN=yes
      addons:
        apt:
          packages:
            - *default_deps
            - [python3.8]
    - env:
      - OPCODE_BIT=5


before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ./build-aux/travis-build.sh
  # "BENCH_TEST=yes" can wait for a long time
  - if [[ "$BENCH_TEST" == "yes" ]]; then travis_wait make bench; fi
