dist: xenial
language: c
sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - texlive-latex-extra
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - tex-gyre
      - help2man
      - latexmk
      - hevea

# env:
#   global:
#     - VERBOSE=1

matrix:
  include:
    - os: linux
    - os: osx
    - compiler: gcc
      env:
        - MATRIX_EVAL="CC=gcc-8 GLOBAL_CONFIGURE_OPTS=--enable-silent-rules"
        # - CFLAGS="-g3 -fsanitize=address -fsanitize=undefined"
        # - LDFLAGS="-fsanitize=address -fsanitize=undefined"
        # - PY_LOG_ENV="LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/7/libasan.so PYTHONMALLOC=malloc"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [gcc-8]

before_install:
  - eval "${MATRIX_EVAL}"

# Run make install so that Python's ctypes.util.find_library works on Python < 3.6
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install help2man ; fi
  - ./bootstrap
  - for flavour in "CPPFLAGS=-DWORD_BYTES=4 -DENDISM=0" "CPPFLAGS=-DWORD_BYTES=4 -DENDISM=1" "CPPFLAGS=-DWORD_BYTES=8 -DENDISM=0" "CPPFLAGS=-DWORD_BYTES=8 -DENDISM=1"; do ./configure $GLOBAL_CONFIGURE_OPTS "$flavour" && make && sudo make install && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make check ; else make distcheck ; fi; done
