language: c
sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - texlive-latex-extra
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - tex-gyre
      - help2man
      - latexmk
      - hevea

env:
  global:
    - VERBOSE=1

matrix:
  include:
    - os: linux
      dist: trusty # Test with Python 3.4, the earliest version we support
    - os: osx
    - os: linux
      dist: xenial
      env:
        - MATRIX_EVAL="CC=gcc-8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [gcc-8]
    - env:
      - ENDISM=0
      - WORD_BYTES=2
    - env:
      - ENDISM=0
      - WORD_BYTES=4
    - env:
      - ENDISM=0
      - WORD_BYTES=8
    - env:
      - ENDISM=1
      - WORD_BYTES=2
    - env:
      - ENDISM=1
      - WORD_BYTES=4
    - env:
      - ENDISM=1
      - WORD_BYTES=8
    - env:
      - CPPFLAGS="-DSMITE_INSTRUCTION_BIT=6"


before_install:
  - eval "${MATRIX_EVAL}"

# Run make install so that Python's ctypes.util.find_library works on Python < 3.6; hence don't use --enable-package-suffix,
# as otherwise the installed libraries will have the wrong name for make distcheck.
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install help2man ; fi
  - ./bootstrap
  - ./configure --enable-silent-rules && make && sudo make install && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make check ; else make distcheck ; fi
