language: c
sudo: true
dist: bionic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &default_deps
      - texlive-latex-extra
      - texlive-science
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - tex-gyre
      - help2man
      - latexmk
      - hevea

env:
  global:
    - VERBOSE=1

matrix:
  include:
    - os: osx
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-8"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_deps
            - [gcc-8]
    - env:
      - ENDISM=0
      - WORD_BYTES=2
    - env:
      - ENDISM=0
      - WORD_BYTES=4
      - BENCH_TEST=yes
    - compiler: clang
      env:
        - ENDISM=0
        - WORD_BYTES=4
        - BENCH_TEST=yes
    - env:
      - ENDISM=0
      - WORD_BYTES=8
      - CONFIGURE_ARGS=(--enable-package-suffix "CFLAGS=\"-g3 -fsanitize=address -fsanitize=undefined\"" "LDFLAGS=\"-fsanitize=address -fsanitize=undefined\"" "PY_LOG_ENV=\"LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/7/libasan.so PYTHONMALLOC=malloc\"")
    - env:
      - ENDISM=1
      - WORD_BYTES=2
    - env:
      - ENDISM=1
      - WORD_BYTES=4
    - env:
      - ENDISM=1
      - WORD_BYTES=8
    - env:
      - OPCODE_BIT=5
    - env:
      - WORD_BYTES=16


before_install:
  - eval "${MATRIX_EVAL}"

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install help2man; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install pyyaml; fi
  - ./bootstrap
  - ./configure --enable-silent-rules "${CONFIGURE_ARGS[@]}" && make
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo make install; fi
  - make check && if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make distcheck; fi
  - if [[ "$BENCH_TEST" == "yes" ]]; then make bench; fi
